// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/grpc/proto/tunnel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevPodWSLService_Start_FullMethodName  = "/tunnel.DevPodWSLService/Start"
	DevPodWSLService_Stop_FullMethodName   = "/tunnel.DevPodWSLService/Stop"
	DevPodWSLService_Exec_FullMethodName   = "/tunnel.DevPodWSLService/Exec"
	DevPodWSLService_Stdin_FullMethodName  = "/tunnel.DevPodWSLService/Stdin"
	DevPodWSLService_Stdout_FullMethodName = "/tunnel.DevPodWSLService/Stdout"
	DevPodWSLService_Stderr_FullMethodName = "/tunnel.DevPodWSLService/Stderr"
	DevPodWSLService_Status_FullMethodName = "/tunnel.DevPodWSLService/Status"
	DevPodWSLService_Upload_FullMethodName = "/tunnel.DevPodWSLService/Upload"
)

// DevPodWSLServiceClient is the client API for DevPodWSLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevPodWSLServiceClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	Stdin(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StdinRequest, Empty], error)
	Stdout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error)
	Stderr(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error)
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentStatus, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, UploadResponse], error)
}

type devPodWSLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevPodWSLServiceClient(cc grpc.ClientConnInterface) DevPodWSLServiceClient {
	return &devPodWSLServiceClient{cc}
}

func (c *devPodWSLServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, DevPodWSLService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devPodWSLServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, DevPodWSLService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devPodWSLServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevPodWSLService_ServiceDesc.Streams[0], DevPodWSLService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_ExecClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *devPodWSLServiceClient) Stdin(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StdinRequest, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevPodWSLService_ServiceDesc.Streams[1], DevPodWSLService_Stdin_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StdinRequest, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_StdinClient = grpc.ClientStreamingClient[StdinRequest, Empty]

func (c *devPodWSLServiceClient) Stdout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevPodWSLService_ServiceDesc.Streams[2], DevPodWSLService_Stdout_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Data]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_StdoutClient = grpc.ServerStreamingClient[Data]

func (c *devPodWSLServiceClient) Stderr(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevPodWSLService_ServiceDesc.Streams[3], DevPodWSLService_Stderr_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Data]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_StderrClient = grpc.ServerStreamingClient[Data]

func (c *devPodWSLServiceClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, DevPodWSLService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devPodWSLServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevPodWSLService_ServiceDesc.Streams[4], DevPodWSLService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_UploadClient = grpc.ClientStreamingClient[Chunk, UploadResponse]

// DevPodWSLServiceServer is the server API for DevPodWSLService service.
// All implementations must embed UnimplementedDevPodWSLServiceServer
// for forward compatibility.
type DevPodWSLServiceServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	Stdin(grpc.ClientStreamingServer[StdinRequest, Empty]) error
	Stdout(*Empty, grpc.ServerStreamingServer[Data]) error
	Stderr(*Empty, grpc.ServerStreamingServer[Data]) error
	Status(context.Context, *Empty) (*AgentStatus, error)
	Upload(grpc.ClientStreamingServer[Chunk, UploadResponse]) error
	mustEmbedUnimplementedDevPodWSLServiceServer()
}

// UnimplementedDevPodWSLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevPodWSLServiceServer struct{}

func (UnimplementedDevPodWSLServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Stdin(grpc.ClientStreamingServer[StdinRequest, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Stdin not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Stdout(*Empty, grpc.ServerStreamingServer[Data]) error {
	return status.Errorf(codes.Unimplemented, "method Stdout not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Stderr(*Empty, grpc.ServerStreamingServer[Data]) error {
	return status.Errorf(codes.Unimplemented, "method Stderr not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Status(context.Context, *Empty) (*AgentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDevPodWSLServiceServer) Upload(grpc.ClientStreamingServer[Chunk, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedDevPodWSLServiceServer) mustEmbedUnimplementedDevPodWSLServiceServer() {}
func (UnimplementedDevPodWSLServiceServer) testEmbeddedByValue()                          {}

// UnsafeDevPodWSLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevPodWSLServiceServer will
// result in compilation errors.
type UnsafeDevPodWSLServiceServer interface {
	mustEmbedUnimplementedDevPodWSLServiceServer()
}

func RegisterDevPodWSLServiceServer(s grpc.ServiceRegistrar, srv DevPodWSLServiceServer) {
	// If the following call pancis, it indicates UnimplementedDevPodWSLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevPodWSLService_ServiceDesc, srv)
}

func _DevPodWSLService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevPodWSLServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevPodWSLService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevPodWSLServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevPodWSLService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevPodWSLServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevPodWSLService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevPodWSLServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevPodWSLService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DevPodWSLServiceServer).Exec(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_ExecServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _DevPodWSLService_Stdin_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DevPodWSLServiceServer).Stdin(&grpc.GenericServerStream[StdinRequest, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_StdinServer = grpc.ClientStreamingServer[StdinRequest, Empty]

func _DevPodWSLService_Stdout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DevPodWSLServiceServer).Stdout(m, &grpc.GenericServerStream[Empty, Data]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_StdoutServer = grpc.ServerStreamingServer[Data]

func _DevPodWSLService_Stderr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DevPodWSLServiceServer).Stderr(m, &grpc.GenericServerStream[Empty, Data]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_StderrServer = grpc.ServerStreamingServer[Data]

func _DevPodWSLService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevPodWSLServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevPodWSLService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevPodWSLServiceServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevPodWSLService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DevPodWSLServiceServer).Upload(&grpc.GenericServerStream[Chunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevPodWSLService_UploadServer = grpc.ClientStreamingServer[Chunk, UploadResponse]

// DevPodWSLService_ServiceDesc is the grpc.ServiceDesc for DevPodWSLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevPodWSLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.DevPodWSLService",
	HandlerType: (*DevPodWSLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _DevPodWSLService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _DevPodWSLService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _DevPodWSLService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _DevPodWSLService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Stdin",
			Handler:       _DevPodWSLService_Stdin_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Stdout",
			Handler:       _DevPodWSLService_Stdout_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stderr",
			Handler:       _DevPodWSLService_Stderr_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _DevPodWSLService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/grpc/proto/tunnel.proto",
}
